# Application configuration (can be overridden by environment variables)
# Postgres connection
pg.host=localhost
pg.port=5432
pg.database=postgres
pg.user=postgres
pg.password=123

# HTTP server
http.port=8082